// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DSS4_ECompliance.BO;
using DSS4_ECompliance.BoTesting.Tests.Common;
using DSS4_ECompliance.DAL;

namespace DSS4_ECompliance.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for tblCustomsFinderTest and is intended
    ///to contain all tblCustomsFinderTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("tblCustomsFinder Repository Tests")]
    [Category("tblCustomsFinder Repository Tests")]
    internal class tblCustomsFinderTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `tblCustomsFinder`")]
        [Order(0)]
        public void tblCustomsFinder_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            new PersistenceSpecification<DSS4_ECompliance.BO.tblCustomsFinder>(Session)
            .CheckProperty(p => p.RiskAnalysys, 6198)
            .CheckProperty(p => p.RisksDetected, 4678)
            .CheckProperty(p => p.CrossBorders, 7408)
            .CheckProperty(p => p.Delays, 7535)
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `tblCustomsFinder`")]
        [Order(1)]
        public void tblCustomsFinder_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DSS4_ECompliance.BO.tblCustomsFinder> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DSS4_ECompliance.BO.tblCustomsFinder>(
                              a => true
                              && (a.RiskAnalysys + 123 > 0)
                              && (a.RisksDetected + 123 > 0)
                              && (a.CrossBorders + 123 > 0)
                              && (a.Delays + 123 > 0)
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}